spring:
  security:
    oauth2:
      client:
        registration:
          wso2:
            client-id: GpDHMnE1zh7qZ6vbrWLm0PSJv9ka
            client-secret: Ah5Ebq3uaHGyLyRBdI5Jfvt5Ktuqi3vUaa4z3ssXAfEa
            scope:
              - openid
              - profile
              - email
              - roles
              - phone
              - groups
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Sample SBA
            provider: wso2
        provider:
          wso2:
            authorization-uri: https://localhost:9443/oauth2/authorize
            token-uri: https://localhost:9443/oauth2/token
            user-info-uri: https://localhost:9443/oauth2/userinfo
            jwk-set-uri: https://localhost:9443/oauth2/jwks
            user-name-attribute: sub
server:
  port: 8000

logging:
  level:
    org.springframework.security: DEBUG